Repository commercelayer/app-customers, pull requests merged in 2024-06, with the labels that each got.

#61 Export 'Main' component as default
  packages/app/src/main.tsx
Labels: enhancement, ignore-for-release

#62 Update all packages to latest major
  package.json
  packages/app/package.json
  packages/app/src/hooks/useCustomerGroupsList.tsx
  packages/app/src/hooks/useCustomerOrdersList.tsx
  packages/app/src/mocks/index.ts
  packages/app/src/mocks/resource.ts
  packages/app/src/pages/CustomerDetails.tsx
  packages/app/src/utils/fetchCustomerGroups.ts
  pnpm-lock.yaml
Labels: enhancement

#63 v1.3.9
  lerna.json
  packages/app/package.json
Labels: ignore-for-release
